= Sången om Allvis

Allvis sade: 
1. »Att bänkarne breda 
skall bruden nu med mig 
i sällskap hemåt hasta. 
För att bli måg jag skyndat, 
det menar nog envar; 
man skall ej hänge sig åt vila hemma.»

Tor sade: 
2. »Vad är det för en bjässe? 
Vi är så blek du på näsan? 
Låg du i natt hos lik? 
Tycke av en turs 
tycks mig hos dig vara. 
Du är ej för bruden boren.»

Allvis sade: 
3. »Allvis jag heter, 
hålles under jorden, 
under sten har jag varaktig stad. 
Betalning för vapen 
att taga jag kommit; 
ingen bindande löfte bryte!»

Tor sade: 
4. »Jag skall bryta, 
ty brudens gifte 
jag främst bestämmer som fader. 
Jag var ej hemma, 
då hon dig lovades; 
enda giftoman bland gudar är jag.»

Allvis sade: 
5. »Vad är det för en man, 
som myndighet påstår 
över fagerglänsande flicka? 
Av folk, som vitt färdas, 
dig få torde känna. 
Vilkens maka har din moder varit?»

Tor sade: 
6. »Ving-Tor jag heter, 
vida jag strövat, 
son jag till Sidgrane är. 
Utan mitt samtycke 
ungmön du ej får 
och gynnas ej med detta gifte.»

Allvis sade: 
7. »Samtycket ditt 
vill snart jag hava 
och gynnas med detta gifte; 
äga vill jag hellre 
än utan vara 
denna mjällvita mö.»

Tor sade: 
8. »Möns älskog 
skall icke förmenad 
varda dig, vise gäst, 
om du ur varje 
värld kan säga 
allt, vad jag veta vill.»

9. »Säg du mig, Allvis - 
alla varelsers öde 
väntar jag, dvärg, att du vet - 
vad månne väl den jord, 
som framför människorna ligger 
heter i varje värld?»

Allvis sade: 
10. »Jord säges bland människor, 
men slätt hos asarne, 
vanerna kallar den vägar; 
alltid grön jättarne, 
alferna den groende, 
gudarne där uppe grus.»

Tor sade: 
11. »Säg du mig, Allvis - 
alla varelsers öde 
väntar jag, dvärg, att du vet - 
vad himmelen, 
som av havet föddes, 
heter i varje värld!»

Allvis sade: 
12. »Himmel den heter bland människor, 
högvalv bland gudar, 
vindvävare kalla den vaner, 
uppvärlden jättar, 
alferna fagertak, 
dvärgarne drypande sal.»

Tor sade: 
13. »Säg du mig, Allvis - 
alla varelsers öde 
väntar jag, dvärg, att du vet - 
huru månen 
som människorna se, 
heter i varje värld!»

Allvis sade: 
14. »Måne den heter bland människor, 
men molntapp hos gudar, 
svänghjul de säga hos Hel, 
skyndaren jättarne 
men skenet dvärgarne, 
om tideräknarn alferna tala.»

Tor sade: 
15. »Säg du mig, Allvis - 
alla varelsers öde 
väntar jag, dvärg, att du vet - 
hur den sol, som människors 
söner skåda, 
heter i varje värld!»

Allvis sade: 
16. »Sol den heter bland människor, 
»sunna» hos gudar, 
den kalla dvärgar Dvalins leksak, 
evigglöd jättar, 
alferna fagerhjul 
och allklar asars söner.»

Tor sade: 
17. »Säg du mig, Allvis - 
alla varelsers öde 
väntar jag, dvärg, att du vet - 
huru de skyar, 
som skicka oss skurar, 
heta i varje värld!»

Allvis sade: 
18. »Skyar de heta hos människor, 
skyfallshopp hos gudar, 
vindflarn dem vanerna kalla, 
ovädersväntan jättarne, 
alferna väderkraft, 
hölje de kallas hos Hel.»

Tor sade: 
19. »Säg du mig, Allvis - 
alla varelsers öde 
väntar jag, dvärg, att du vet - 
huru vinden, 
som vidast far, 
heter i varje värld!»

Allvis sade: 
20. »Vind den heter bland människor, 
viftaren hos gudar, 
gnäggarn hos de väldiga väsen, 
gormaren hos jättar, 
snyftaren hos alfer, 
vinaren han heter hos Hel.»

Tor sade: 
21. »Säg du mig, Allvis - 
alla varelsers öde 
väntar jag, dvärg, att du vet - 
huru lugnet, 
som ligga plär, 
heter i varje värld!»

Allvis sade: 
22. »Lugn det heter hos människor, 
lindring hos gudar, 
vindslut det vanerna kalla, 
övervärme jättarne, 
alferna dagsstillhet, 
dvärgarne dagens ro.»

Tor sade: 
23. »Säg mig du, Allvis - 
alla varelsers öde 
väntar jag, dvärg, att du vet - 
huru den sjön, 
som skepp ro på, 
heter i varje värld!»

Allvis sade: 
24. »Sjö den heter bland människor, 
vida skivan hos gudar, 
vanerna kalla den våg, 
jättarne ålhem 
alferna vätskeämne, 
namnet djupt hav giva den dvärgar.»

Tor sade: 
25. »Säg mig du, Allvis - 
alla varelsers öde 
väntar jag, dvärg, att du vet - 
huru elden, 
som för allt folk brinner, 
heter i varje värld!»

Allvis sade: 
26. »Eld den heter bland människor, 
men bland asarne flamma, 
vanerna kalla den våg, 
jättarne slukaren, 
den svedande dvärgar, 
den hastige han kallas hos Hel.»

Tor sade: 
27. »Säg mig du, Allvis - 
alla varelsers öde 
väntar jag, dvärg, att du vet - 
huru skogen, 
som skuggar människorna, 
heter i varje värld!»

Allvis sade: 
28. »Skog den heter hos människor, 
man på slätten hos gudar, 
hos Hels folk höjdsidans tång, 
eldaren hos jättar, 
hos alferna fagergrenig, 
hos vise vaner spö.»

Tor sade: 
29. »Säg mig du, Allvis - 
alla varelsers öde 
väntar jag, dvärg, att du vet - 
huru natten, 
Norves dotter, 
heter i varje värld!»

Allvis sade: 
30. »Natt hon heter bland människor, 
mörker bland gudar, 
mask kalla henne väldiga makter, 
oljus jättarne, 
alferna sömngumman, 
drömväverska kalla henne dvärgar.»

Tor sade: 
31. »Säg mig du, Allvis - 
alla varelsers öde 
väntar jag, dvärg, att du vet - 
huru säden, 
som sås av människorna, 
heter i varje värld!»

Allvis sade: 
32. »Bjugg den heter bland människor 
och 'barr' hos gudar, 
hos vanerna heter den växt, 
äta jättarne den kalla, 
alferna vätskeämne, 
hänghuvud heter den hos Hel.»

Tor sade: 
33. »Säg mig du, Allvis - 
alla varelsers öde 
väntar jag, dvärg, att du vet - 
huru ölet, 
som allt folk dricker, 
heter i varje värld!»

Allvis sade: 
34. »Öl det heter bland människor, 
bland asarne brygd, 
rusande vätska hos vaner, 
klar dryck det heter hos jättar 
och kallas mjöd hos Hel, 
supning hos Suttungs söner.»

Tor sade: 
35. »I ett bröst 
jag aldrig såg 
så många minne från fordom. 
Dock av mycket svek 
nu sviken du är: 
kvar uppe till dagsljus, dvärg! 
Nu skiner solen i salen.»