= Groas trollsång

Sonen sade:

[verse]
1. »Vakna nu, Groa! 
Vakna, goda kvinna! 
Dig jag väcker vid de dödas dörrar, 
om du minnes det, 
att du manade din son 
att komma till kumlet vid din grav.»

Modern sade:

[verse]
2. »Vad angeläget har 
min enda son? 
Vad ont har överfallit dig, 
då din moder du kallar, 
som i mullen är kommen 
och ur människors värld har vandrat?»

Sonen sade:

[verse]
3. »Ett styggt spelbord 
ställde åt mig onda kvinnan, 
hon som famnade min fader, 
då hon bjöd mig vandra, 
dit man vet är omöjligt, 
till möte med Menglod.»

Modern sade:

[verse]
4. »Lång är färden, 
farvägar långa, 
lång är människors längtan. 
Om det varder så, 
att din vilja du får, 
efter nornors skön det då sker.»

Sonen sade:

[verse]
»Sjung för mig galdrar, 
som goda äro! 
Bärga, moder, ditt barn! 
Jag är rädd, att på vägen 
jag råkar i olycka. 
En yngling för ung jag är.»

Modern sade:

[verse]
»Jag sjunger dig den första, 
som man fördelaktig säger 
- den sjöng Rane för Rind - 
att från axeln du skjuter, 
vad dig elakt tyckes. 
Led du själv dig själv!

[verse]
7. Den andra jag dig sjunger, 
om ute på vägar 
du skall utan glädje gå. 
Nornans huldhet 
dig hägne överallt, 
fast du dig smädad ser!

[verse]
8. Jag sjunger dig den tredje, 
om sjudande älvar 
dig forsa till livets förlust. 
Horn och Rud hädan 
till Hel strömma, 
men städs minskas de må för dig!

[verse]
9. Den fjärde jag dig sjunger, 
om fiender stå 
färdiga att föra dig till galgen. 
Deras håg må sig ändra 
till hugnad för dig, 
deras sinne till vänskap sig vända!

[verse]
10. Den femte jag dig sjunger, 
om fjättrar bliva 
dig bundna om armar och ben. 
Lösetrollsång låter jag 
framför läggen sjungas, 
låset då av lemmarna springer, 
och ifrån fötterna fjättern.

[verse]
11. Den sjätte jag dig sjunger, 
om i sjögång du kommer 
varre, än någon vet. 
Lugn på sjö 
i ditt skepp må komma 
och förläne dig fridsäll färd!

[verse]
12. Den sjunde jag dig sjunger, 
om med skärpa dig kniper 
frosten på höga fjället. 
Må likens kyla 
ditt kött ej fördärva! 
Må hullet vid lemmarne hållas!

[verse]
13. Jag sjunger dig den åttonde, 
om på skymningens väg 
du nås av natten ute, 
att dess mindre måtte 
dig men göra 
en kristen död kvinna.

[verse]
14. Jag sjunger dig den nionde, 
om du skiftar ord 
med resen, som rosar sig av vapen. 
Må mål och mannavett 
i minne och hjärta 
dig givas nog att dig hjälpa!

[verse]
15. Far du nu aldrig, 
där fara är uppenbar, 
och må ogagn din älskog ej hindra! 
På jordfast sten 
jag stod inom dörrgången, 
medan dig trollsång jag täljde.

[verse]
16. Bär med dig härifrån 
din moders ord, son, 
och låt dem bo i ditt bröst, 
ty lycka till fullo 
skall i livet du ha, 
så länge du mina ord minnes.»
