= Tredje kvädet om Gudrun

Herkja hette Atles trälkvinna; hon hade varit hans frilla.
Hon sade för Atle, att hon hade sett Tjodrek och Gudrun tillsammans.
Atle var då mycket ledsen.

Då sade Gudrun: 
1. »Varför är du, Atle, 
alltid, du Budles son, 
ledsen till sinnes? 
Vi ler du aldrig? 
Mer gärna ville 
jarlarne väl, 
att vid män du talte 
och mig såge.»

Atle svarade: 
2. »Mig grämer, Gudrun, 
Gjukes dotter, 
vad Herkja mig 
i hallen sade, 
att hon såg dig och Tjodrek 
sova under täcket 
och lägga kärligt 
linnet om er.»

3. »Dig om allt det 
eder jag svärja 
vill vid den heliga 
vita stenen, 
att jag med Tjodrek 
gjorde ej sådant, 
som kvinna eller man 
ej kunde få företa.

4. Blott en enda gång 
den orädde fursten, 
härarnes hövding 
om halsen jag föll. 
Andra voro 
våra samtal, 
då vi två sorgsna 
tillsamman språkade.

5. Till oss kom Tjodrek 
med trettio man, 
ingen enda lever 
av alla de trettio. 
Du avhänt mig broder 
och brynjeklädda kämpar, 
du avhänt mig samtliga 
släktingar, de närmaste.

6. Sänd efter Saxe, 
södermännens furste, 
han kan viga vattnet 
i vällande kittel.»

7. Sju hundraden män 
in i hallen gingo, 
innan konungens hustru 
stack handen i kitteln.

Gudrun sade: 
8. »Nu kommer ej Gunnar, 
nu kallar jag ej Hogne, 
aldrig mer jag ser 
mina älskade bröder. 
Med svärd skulle Hogne 
slik orätt hämna, 
nu har jag själv att visa 
beskyllningens falskhet.»

9. Till bottnen hon sträckte 
bländvit handlove, 
och upp hon tog 
ädelstenar. 
»Skåden nu, män, 
skuldlös är jag vorden, 
genom heligt prov, 
hur än kitteln sjuder.»

10. Då jublade Atles 
hjärta i bröstet, 
då Gudruns händer 
han hela såg: 
»Nu skall Herkja 
hit till kitteln, 
hon, som skyllde Gudrun 
för skändlighet.»

11. Något ömkligt den ej såg, 
som ej åsåg det, 
hur på Herkja 
händerna skållades. 
Ned i ruttnande kärr 
de körde den mön. 
Så blev oförrätten Gudrun 
återgäldad.