= Sången om Hamder

[verse]
1. Sorgliga sysslor 
sattes i gång 
en glädjelös morgon 
på gården framför dörren. 
Tidigt på morgonen 
många bekymmer 
över världens ve 
väcka sorgen.

[verse]
2. Ej har det skett nu, 
ej heller i går, 
lång tid har 
lidit sedan dess, 
få ting äro så forna, 
att det ej framom är i ålder, 
då Gudrun manade, 
Gjukes dotter, 
sina unga söner 
att Svanhild hämna.

[verse]
3. »Eder syster 
Svanhild hette, 
som Jormunrek 
givit att trampas 
på stora vägen 
av vita och svarta, 
gråa, gångvana 
gotiska hästar.

[verse]
4. Tillbaka I ären trängda 
fast båda konungar; 
av alla ättens grenar 
I ensamma leven.

[verse]
5. Ensam jag blivit 
som asp i skogsbacken, 
fränder från mig fallit, 
som från furan kvistar, 
förlamad är livsfröjd 
som lövet på trädet, 
då kvistsvedande sol 
kommer en het dag.»

[verse]
6. Då sade Hamder 
i hågen djärv: 
»Högt du ej lovade 
Hognes gärning, 
när Sigurd de väckte 
ur sömnen upp. 
Du satt på bädden, 
men banemännen skrattade.

[verse]
7. Dina blåvita täcken 
i blod av din man 
färgades röda, 
flöto i mordvätska. 
Då dog Sigurd; 
hos den döde du satt, 
glömsk av all glädje; 
så Gunnar dig velat.

[verse]
8. Mot Atle du ämnade strida 
genom att Erp mörda 
och Eitils liv taga; 
det ännu värre dig själv var. 
Så mot annan var och en 
till dess ofärd sig må värja 
med sårbitande svärd, 
att han sig därvid ej skadar.»

[verse]
9. Det sade då Sorle, 
snabbtänkt han var: 
»Mot vår moder jag vill ej 
motstridig vara. 
Ett ord tyckes än osagt 
av eder båda vara. 
Varom beder du nu, Gudrun, 
som till din gråt du ej får?

[verse]
10. Begråt dina bröder 
och barnen kära, 
dina nära fränder 
förda i striden! 
Oss båda ock, Gudrun, 
begråta skall du, 
som här dödsvigda rida; 
dö vi skola fjärran.»

[verse]
11. Det talade den stolta, 
stod ovan dem hon skyddat, 
smalfingrad hon sade 
till sonen detta. 
- - - - - - - - - - - - 
- - - - - - - - - - - - 
ty fara då finnes 
att i fred icke mäkta 
två män ensamma 
tio hundra goter, 
binda och besegra 
i borgen den höga.»

[verse]
12. I rasande vrede 
de redo ut från gården 
och sågo på gatan 
sin sluge halvbror: 
»Vad bistånd vill oss 
brunhåringen giva?»

[verse]
13. Halvbrodern svarade 
och sade sig skola 
hjälpa sina fränder 
som en fot den andre. 
»Vad kan ena foten 
den andre hjälp giva 
eller handen, som hänga 
vid hullet, åt den andra?

[verse]
14. Ännu en gång 
Erp då talade, 
härlig han lekte 
på hästens rygg: 
»Vanskligt är att visa 
vägen åt en feg.» 
Oförskräckt man säger 
en oäkting vara.

[verse]
15. De drogo ur skidan 
skidejärnet, 
svärdets eggar, 
till sötma för Hel. 
Sin makt med en tredjedel 
minskade de, 
läto unge mannen 
till marken segna.

[verse]
16. Över fuktiga fjäll 
färdades de unge 
på hunniska hästar 
att hämna mordet. 
De skakade sina kappor, 
sina klingor omgjordade, 
de ädelborna satte 
silkeskläder på.

[verse]
17. Framåt förde vägen, 
de funno olycksstigar, 
och systerns son 
hängd sårad på trädstammen, 
vindkalla vargträdet 
väster om byn; 
tranans kost där krälade. 
kusligt var att bida.

[verse]
18. Glam var i hallen 
de voro glada av ölet, 
och hörde icke 
hästarne komma, 
förrän modige kämpen 
tjöt uti hornet.

[verse]
19. För Jormunrek 
de gingo att säga, 
att varsnade voro 
väpnade med hjälmar. 
»Styren om råd, 
ty stormän hava kommit, 
för mäktiga män 
ni mön låtit trampa.»

[verse]
20. Storskrattade då Jormunrek, 
mustaschen drog med handen, 
önskade till sin ofärd, 
uppeggade sig vid vinet. 
Sitt bruna hår han skakade, 
på blanka skölden såg, 
lät guldbägaren 
gunga i handen.

[verse]
21. »Säll jag mig syntes, 
om se jag kunde 
Hamder och Sorle 
här i salen; 
med bågsträngar båda 
jag binda skulle, 
Gjukes goda barn 
på galgen fästa.»

[verse]
22. Strid blev i huset, 
ned störtade bägare 
i blodet, där männen lågo, 
ur bröstet på goter kommet.

[verse]
23. Då sade Hamder, 
i hågen djärv: 
»Du önskade, Jormunrek, 
att oss få se komma, 
bröder med samma moder, 
i borgen din. 
Du ser dina fötter, 
du ser dina händer 
slungade, Jormunrek, 
i svedande eld.»

[verse]
24. Då röt den gamle 
från gudarne stammande 
fursten i brynja, 
som björnen ryter: 
»Kasten sten på männen, 
då de stå emot spjuten, 
då järn icke biter 
på Jonakrs söner!»

[verse]
25. Det sade då Hamder 
i hågen djärv: 
»Ej bra var det broder, 
att den bälgen du löste; 
fördärvliga råd 
rikligt ur den komma.»

Sorle sade: 

[verse]
26. »Mod hade du, Hamder, 
blott hovsamhet du hade; 
på en människa felas mycket, 
då manvett fattas.»

Hamder sade: 

[verse]
27. Av vore nu ock huvudet, 
om Erp levde, 
vår vapendjärve broder, 
som på vägen vi dräpte, 
den modige mannen 
- därtill manade diser - 
han som skyddade sig i striden; 
vi skickade oss då till kamp.»

Sorle sade: 

[verse]
28. »Ej oss anstår 
ulvars vana 
att sak med varandra söka, 
likt nornors gråa, 
glupska hundar, 
som i ödemarken avlas.

[verse]
29. Väl hava vi stridit 
vi stå över goter, 
som av eggarne ödda blivit, 
liksom örnar på kvist. 
Gott namn ha vi vunnit, 
dö vi nu eller i morgon; 
till kvällen ej lever 
den som kallats av 
nornor.»

[verse]
30. Där foll Sorle 
vid salens gavel, 
och Hamder stupade 
vid husets bakvägg.

Detta kallas gamla Hamdismal.
