= Nivlungarnes dråp

Gunnar och Hogne togo då allt guldet, Favners arv.
Ofrid var då mellan gjukungarne och Atle; han tillskrev gjukungarne skulden till Brynhilds död.
Till förlikning bestämdes, att de skulle gifta Gudrun med honom, och de gåvo henne glömskedryck att dricka, innan hon jakade till att gifta sig med Atle.
Atles söner voro Erp och Eitil, men Svanhild var Sigurds och Gudruns dotter.
Konung Atle bjöd hem Gunnar och Hogne och sände Vinge eller Knefröd.
Gudrun kände sveket och skickade hälsning med runor, att de icke skulle komma, och till kännemärke sände hon Hogne ringen Andvaranaut och knöt i varghår.
Gunnar hade friat till Oddrun, Atles syster, och fick henne icke; därpå gifte han sig med Glaumvor, men Hogne var gift med Kostbera; deras söner voro Solar och Snävar och Gjuke.
Men när gjukungarne kommo till Atle, så bad Gudrun sina söner, att de skulle bedja för gjukungarnes liv, men de ville icke.
Hjärtat skars ur Hogne, men Gunnar sattes i ormgård.
Han slog harpan och sövde ormarne, men en huggorm stack honom i levern.
