= Solsången

1. Rikedom och liv
rånade från människor
den bistre busen;
över den väg,
som vaktades av honom,
kunde ingen levande lända.

2. Allra oftast
ensam åt han;
aldrig bjöd han man till mat,
förrän det kom
en kraftlös gäst
vandrande, av vägen trött.

3. Att han tarvade dryck,
den trötte sade,
och att mindre mätt han vore.
Med bävande hjärta
till den boning han litade,
som förr varit full av ont.

4. Mat gav han och dryck
åt den, som dödstrött var,
allt med uppriktigt sinne.
På Guds bud han aktade,
med gott honom fägnade,
ty eländig ansågs han vara.

5. Den andre stod upp
och ont han tänkte,
ej tog han emot med tack.
Synden svällde.
I sömnen han mördade
den kloke, som förr kunnat sig akta.

6. Då han huggen vaknade,
bad han himlarnas Gud,
att hjälp han måtte honom giva,
men på sig den andre
fick synden taga,
då en saklös han svikit hade.

7. Heliga änglar
ur himlen kommo ned
och förenade hans ande med sig;
i ett rent liv
han leva skall
evigt med allsäktig Gud.

8. För rikedom och hälsa
råder ingen man,
om det än går honom gott.
Mången angripes
av vad minst han anar;
för sin frid råder ingen ensam.

9. Icke tänkte
Unnar och Sävalde,
att lyckan dem lämna skulle.
Nakna de blevo
och nödställda,
skrämdes som vargar till skogs.

10. Lustans makt
varit mången till sorg,
ofta kommer kval från kvinnor.
Till men de bli,
fast mäktige Gud
dem skapade till köttets kyskhet.

11. Svavad och Skarthedin
i sämja levde;
ej den ene kunde vara utan den andre,
förrn besinning de miste
för samma kvinna;
till last hon levde för dem.

12. Om intet de sig brydde
för den bländvita mön,
ej om gyckel, ej ljusa dagar;
intet annat
önska de kunde
än den strålande sköna gestalt.

13. Dystra blevo dem
de dunkla nätterna;
ingen ljuvlig sömn de sovo,
och av denna harm
hätskhet föddes
mellan de verkliga vänner.

14. Oerhörda dåd
oftast bliva
i vrede vedergällda.
I holmgång de stredo
om det hulda viv
och fingo båda sin bane.

15. Övermod hysa
skall ingen människa;
det har jag sannerligen sett;
ty de flesta av dem,
som förfalla till högfärd
bort ifrån Gud gå.

16. De rådde över mycket
Radny och Vebode
och visste sig gott blott verka.
Nu de sitta
och såren vända
ömsom eldarna till.

17. På sig de trodde
och tyckte sig vara
ensamma över allt folk,
men allsmäktig Gud
annorlunda
lämpade livet för dem.

18. De mättade sin lusta
på många sätt
och hade sin glädje i guld.
Nu vedergälls dem,
då vandra de skola
emellan eld och is.

19. På dina ovänner
må aldrig du lita,
fast vackra ord de välja.
Gott må du lova dem,
ty gott är att varning
av annans olycka taga.

20. Så det gick honom,
Sorle den godsinte,
då i Vigulvs våld han sig gav.
Säkert han honom trodde
men för svek blev ett offer
av sin broders baneman.

21. Han gav dem lejd
av ett gott hjärta
och de lovade att lämna honom guld;
försonade de sade sig,
när tillsammans de drucko,
men falskhet kom dock fram.

22. Men efteråt
på andra dagen,
då de hade in i Rygjardal ridit,
med svärd de stympade
den, som saklös var,
och läto hans liv fara.

23. Hans lik de drogo
till lönlig plats
och bragte det ned i en brunn;
förhemliga det ville de,
men Herren Gud
helig i himlen det såg.

24. Hans ande bjöd
allsmäktig Gud
gå i sin glädje in,
men sent skola
de sakskyldige
från kvalen kallade bli.

25. Bed Herrans ords
hägnande diser
dig bevågna vara.
I veckan efter
enligt din viljas
önskan skall allting gå.

26. De vredens verk,
som du vrångt förövat,
försona ej åter med ont!
Med godhet skall du trösta
den, du gråta låtit,
det skänker själen heder.

27. Gud skall man åkalla
om goda ting,
den mäktige, som människorna skapat.
Mycket för den man
menligt bliver,
som är sen att söka sin fader.

28. Dig bedja höves
med brinnande iver
om det, som tyckes dig tarvas,
ty allting blir den utan,
som ingenting beder;
få tänka på den tigandes behov.

29. Sent jag kom,
fast kallad tidigt,
till domhavandens dörrar.
Dit jag mig tänker,
ty det lovades mig;
välfägnad den får, som den fordrar.

30. Synderna vålla,
att med sorg vi fara
ur denna våndans värld.
Ingen ängslas,
som ej ont gör;
det är gott utan vank att vara.

31. Ulvar lika
tyckas alla de,
som ombytlig hug hava.
Så vedergälles dem,
att de vandra skola
till straff på glödande gator.

32. Vänliga råd,
med vett förbundna,
sju tillhopa jag låter dig lära.
Minns dem noga,
och missakta dem aldrig;
nyttiga äro alla att njuta.

33. Därom är att säga,
hur säll jag var
i välbehagliga världen,
och å andra sidan
hur ytterst motvilligt
de dödlige gå emot döden.
34. Lystnad och dårskap
förleder människor,
som fika efter gods och guld.
De blanka slantar
till sorg bliva lång;
förmögenhet gjort mången till dåre.

35. Glad åt mycket
jag människor syntes,
ty få saker visste jag på förhand.
Världen, där vi dväljas,
danade Herren
full av fröjd och lust.

36. Lutande jag satt
och länge var jag nedböjd;
mycket lysten jag var då att leva.
Men han mätte min tid,
som mäktig var;
för den, som dö skall, är vägen visad.

37. Dödsgudinnan Hels rep
hårt drogos åt
och snärjde mina sidor.
Slita dem jag ville,
men sega de voro;
lättsamt är att lös få gå.

38. Ensam jag kände,
hur på alla håll
smärtor i mig svällde.
Hels möar bjödo
mig hem varje afton,
i det jag huttrade och hackade tänder.

39. Solen jag såg,
den samma dagstjärnan,
luta till nedgång i larmvärlden,
men på annat håll hörde jag
Hels grind tungt
på sina gångjärn gnissla.

40. Solen jag såg sjunka
med sken, som av blod;
ur världen då stupade min väg.
Mäktig hon mig syntes
på många sätt,
emot vad jag förr henne funnit.

41. Solen jag såg,
och det syntes mig
som om Herrens härlighet jag såge
och för henne sista gången
mitt huvud jag böjde,
som jag gjorde det här uppå jorden.

42. Solen jag såg
och så hon strålade,
att min sans jag tyckte försvinna,
men Gylvs strömmar
stormade på annat håll,
blandade mycket med blod.

43. Solen jag såg,
och vid synen jag skälvde,
av farhåga full och bedrövad,
ty mitt hjärta var
allt igenom
söndergånget i slamsor.

44. Solen jag såg,
sällan mer bedrövad;
ur världen då stupade min väg.
Min tunga var
som trä räknade
och utanpå kroppen allt kallnat.

45. Solen jag såg,
sedan ej mera
efter denna dystra dag,
ty fjällvattnen slöto sig
samma för mig
och jag gick bort, kallad från kvalen.

46. Hoppets stjärna flög
- och då född jag blev -
bort ifrån mitt bröst;
högt hon flög.
fäste saknade,
att till vila hon komma kunde.

47. Längre än alla
var den enda natt,
då stel jag låg på strå.
Då i sanning man ser,
vad som sagts av Gud,
att människan är mullens son.

48. Det höre och akte
barmhärtig Gud,
som himmel och jord haver gjort,
hur mol allena
många vandra,
fast till släktingar sig sälla de skulle.

49. Sina gärningars frukt
får envar njuta;
säll den, som glad gör gott,
då av mitt överflöd
mig ämnad var
en säng i sanden bäddad.

50. Köttets lusta
lockar ofta människor,
mången för mycken den har,
ty varmbadens vatten
var mig ledast
framför alla övriga ting.

51. På nornors stol
jag nio dagar satt,
därifrån lyftes jag högt på häst,
då Hels sol
hiskligt sken
ur mulna himmelens moln.

52. Utanför och innanför
alla sju segervärldar
förföll det mig, att jag for.
I höjden och djupet
jag hitta sökte,
var leden var lättast framkomlig.

53. Att säga nu är,
vad jag såg allra först,
när i kvalens värld jag var kommen.
Svedda fåglar,
framlidna själar,
flögo så många som mygg.

54. Från väster jag såg
Vans drakar flyga
och en eldvåg efter sig lämna.
Vingarna de skakade,
så att vida mig tycktes
himmel och hälleberg rämna.

55. Solens hjort
från söder såg jag fara,
honom tyglade tvenne tillsamman.
Hans fötter stodo
på flata marken,
men hornen snuddade vid himlen.

56. Från norr såg jag rida
Nides söner,
jag såg dem sju tillsamman.
Ur fulla horn
härligt mjöd de drucko
från Baugregins brunn.

57. Vinden tystnade,
vattnen stannade,
då hörde jag ett gräsligt gny.
Åt sina män
malde trolösa kvinnor
mull, till mat ämnad.

58. Blodiga kvarnstenar
dess kvinnor mörka
med bedrövat sinne drogo.
Deras blodiga hjärtan
utanför bröstet hängde,
tröttade av tunga kval.

59. Mången man,
som jag mötte där,
gick stympad på glödande gata.
Deras anleten
alla mig tycktes
sudlade av brudars blod.

60. Många män jag såg
ned i mullen gångna,
som nattvard ej njuta fingo.
Hedna stjärnor stodo
över huvudet på dem,
ristade med fördärvets runor.

61. Män jag såg
som mycken avund
över nästans förhållanden nära.
Blodiga runor
på bröstet på dem voro
märkta för dem till men.

62. Män jag såg där
många oglada,
vilse de voro om vägen.
Det får den till lön,
som förföra sig låter,
av denna världs olyckor drabbad.

63. Män jag såg,
som med många svek
efter andras egendom traktat.
I flockar de foro
till Fregjarns borg
och hade bördor av bly.

64. Män jag såg,
som många hade
på liv och rikedom rånat.
Bröstet på dessa
bets igenom
av ormar, som svällde av etter.

65. Män jag såg,
som mycket ogärna
helgdagar hålla ville.
Deras händer voro
på heta stenar
naglade fast med nödtvång.

66. Män jag såg,
som av mycken stolthet
förhävde sig högre än vån var.
Eldslågor
på ett underligt sätt
kring deras kläder slogo.

67. Män jag såg,
som mången gång
hade ord på andra ljugit.
Hels korpar
ur huvudet på dem
hårdligen ögonen höggo.

68. All den skräck
får du icke veta,
som de till dödsriket gångna drabbar.
Söta synder
till svår bot varda;
ve kommer alltid efter vällust.

69. Män jag såg,
som mycket gods,
som gåva efter Guds lag givit.
Härliga ljus
över huvudet på dem
bjärt lysande brunno.

70. Män jag såg,
som med mycken iver
främjat fattigas väl.
Heliga böcker
och himlaskrift läste
änglar över deras huvud.

71. Män jag såg,
som mycket illa
farit hade genom fasta.
Guds änglar sig bugade
för alla dessa;
det är den högsta hugnad.

72. Män jag såg,
som sörjt för sin moder
och givit henne mat i mun.
Deras vilorum voro
vackert pyntade,
ställda på himmelens strålar.

73. De heliga möar
hade rentvagit
själen från syndens smitta,
av sådana män,
som mången dag
sig själva plågat och pinat.

74. Höga vagnar såg jag
längs himlarne fara;
gång de äga till Gud.
Dem styra de män,
som mördade äro
för alls ingen orsak.

75. Allsmäktig fader,
lika mäktige son,
och du himmelens helige ande!
Dig beder jag oss skilja,
du som själv oss skapat,
från allt, som ont är.

76. Bjugvor och Listvor
sitta i Herders dörrar
uppå orgelstolen.
Järnens blod
göts ur deras näsa
och fiendskap väcker bland folk.

77. Odens viv,
vällustlysten,
på jordens fartyg färdas.
Hennes segel
sent bärgas,
som på trängtans tackling sitta.

78. O son, din fader
har framställt tydningen
jämte Solkatlas söner,
av det horn av hjort,
som ur högen bar
den vise Vigdvalin.

79. Här äro runor
som ristat hava
Njords nio döttrar.
Radveig är den äldsta,
den yngsta Kreppvor,
tillsammans med systrar sju.

80. Allt slags ont
de övat hava
Svavr och Svavrlogi.
De blodvite gjorde
och banesår sögo
av evig ondskefull vana.

81. Detta kväde,
som dig kungjort jag har
skall du för levande läsa.
Solens sång
som synas skall
långtifrån lögnaktig vara.

82. Må vi här skiljas
och mötas åter
på folkens fröjdedag!
Du, Herre, giv
de hädangångne ro
och dem hjälp, som på jorden leva!

83. Dyrbar visdom
i drömmen dig sades
och sanning då du såg.
Ingen människa
så mångkunnig skaptes,
att förr hon hört Solsångens saga.
