name: build asciidoc

on:
  push:
    branches:
      - main
jobs:
  asciidoc_build:
    runs-on: ubuntu-18.04
    name: Build Asciidoc
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build PDF
        uses: avattathil/asciidoctor-action@master
        with:
          program: "gem install bundler && bundle install && rake"

      - name: Upload Ebook Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Ebook documents
          path: |
            build/eddan.pdf
            build/eddan.epub
            build/eddan.html
